# Generated by Django 3.2 on 2021-04-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
