# Generated by Django 3.2 on 2021-04-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0002_myinfo_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
    ]
